# Generated by Django 5.0.1 on 2024-02-26 08:33

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('status', models.CharField(choices=[('COMPLETED', 'Завершен'), ('PENDING', 'В процессе'), ('CANCELLED', 'Отменен')], max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'db_table': 'carts_carts',
            },
            managers=[
                ('cart_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
